on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

name: Docker-Image-Build

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tsukisuperior/sdl2-docker:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
